// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_esiwnbHQxSqKe8U9PlEZmIl-bQRCeos',
    appId: '1:315610154854:web:15716ebd117d3ac34feaa7',
    messagingSenderId: '315610154854',
    projectId: 'foodel-5e71b',
    authDomain: 'foodel-5e71b.firebaseapp.com',
    storageBucket: 'foodel-5e71b.firebasestorage.app',
    measurementId: 'G-EGWP813CML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKJJ8ZkAuC5uw9sKiJNWFeEZralHfcqI',
    appId: '1:315610154854:android:662a537b891b706d4feaa7',
    messagingSenderId: '315610154854',
    projectId: 'foodel-5e71b',
    storageBucket: 'foodel-5e71b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzkhtj6Jxz4rxgbiDYjFgMJSkl3fql7Q',
    appId: '1:315610154854:ios:de4d3077e308cb584feaa7',
    messagingSenderId: '315610154854',
    projectId: 'foodel-5e71b',
    storageBucket: 'foodel-5e71b.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATzkhtj6Jxz4rxgbiDYjFgMJSkl3fql7Q',
    appId: '1:315610154854:ios:de4d3077e308cb584feaa7',
    messagingSenderId: '315610154854',
    projectId: 'foodel-5e71b',
    storageBucket: 'foodel-5e71b.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_esiwnbHQxSqKe8U9PlEZmIl-bQRCeos',
    appId: '1:315610154854:web:51737f5baa86b1534feaa7',
    messagingSenderId: '315610154854',
    projectId: 'foodel-5e71b',
    authDomain: 'foodel-5e71b.firebaseapp.com',
    storageBucket: 'foodel-5e71b.firebasestorage.app',
    measurementId: 'G-RF739ZG3XW',
  );

}